resolutions = [ 1024,]
enable_ar_bucket = true
min_ar = 0.5
max_ar = 2.0
num_ar_buckets = 7
frame_buckets = [ 1,]
pad_last_batch = true
[[directory]]
path = "/workspace/krea2_v2_data/target"
control_path = "/workspace/krea2_v2_data/control"
num_repeats = 1
