[program:k2ab_legacy]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/k2ab_legacy.sh
autostart=false
autorestart=unexpected
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
